### ISSUE TITLE
Error in Pills

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#100]
When i try to edit an entry i get this error.
```
2023-05-30T17:34:01+00:00	CRITICAL 87.165.127.237	error	Uncaught Throwable of type Error thrown with message "Call to a member function get() on int". Stack trace: #0 [ROOT]/libraries/src/HTML/HTMLHelper.php(292): JHTMLMrelements::pills()
#1 [ROOT]/libraries/src/HTML/HTMLHelper.php(128): Joomla\CMS\HTML\HTMLHelper::call()
#2 [ROOT]/components/com_joomcck/fields/listautocomplete/listautocomplete.php(44): Joomla\CMS\HTML\HTMLHelper::_()
#3 [ROOT]/components/com_joomcck/views/form/view.html.php(517): JFormFieldCListautocomplete->getInput()
#4 [ROOT]/components/com_joomcck/views/form/view.html.php(233): JoomcckViewForm->_prepareFields()
#5 [ROOT]/libraries/mint/mvc/controller/base.php(688): JoomcckViewForm->display()
#6 [ROOT]/components/com_joomcck/controller.php(89): MControllerBase->display()
#7 [ROOT]/libraries/mint/mvc/controller/base.php(725): JoomcckController->display()
#8 [ROOT]/components/com_joomcck/joomcck.php(46): MControllerBase->execute()
#9 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): require_once('...')
#10 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(73): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()
#11 [ROOT]/libraries/src/Component/ComponentHelper.php(361): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#12 [ROOT]/libraries/src/Application/SiteApplication.php(208): Joomla\CMS\Component\ComponentHelper::renderComponent()
#13 [ROOT]/libraries/src/Application/SiteApplication.php(249): Joomla\CMS\Application\SiteApplication->dispatch()
#14 [ROOT]/libraries/src/Application/CMSApplication.php(293): Joomla\CMS\Application\SiteApplication->doExecute()
#15 [ROOT]/includes/app.php(61): Joomla\CMS\Application\CMSApplication->execute()
#16 [ROOT]/index.php(32): require_once('...')
#17 {main}
```

**Comment by andiamine** [comment]
thanks for reporting this issue, i will check it and update :)
JoomCCK is getting better and has many hidden features.

**Comment by LordHelmchen666** [comment]
> thanks for reporting this issue, i will check it and update :) JoomCCK is getting better and has many hidden features.

Yes you are right, but this also means a lot of little bugs. :)
Thanks for all your time you put in this project.

**Comment by andiamine** [comment]
Issue fixed
